name: ydtind
description: yiddishland.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  flutter_staggered_grid_view: ^0.7.0
  percent_indicator: ^4.2.3
  image_picker: ^0.8.4+2
  firebase_storage: ^11.7.6
  get: ^4.6.6
  image_cropper: ^7.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# Supported platforms
platforms:
  android:
  ios:
  web:
  macos: